### ISSUE TITLE
`@eslint-community/eslint-comments/disable-enable-pair` crash in HTML files

### ISSUE THREAD

**Issue by Samuel-Therrien-Beslogic** [eslint-community/eslint-plugin-eslint-comments#162]
Version: `@eslint-community/eslint-plugin-eslint-comments@4.1.0`

`.eslintrc.json`
```json
  "rules": {
    "@eslint-community/eslint-comments/disable-enable-pair": [
      "error",
      {
        "allowWholeFile": true
      }
    ]
  },
```

Error:
```
Oops! Something went wrong! :(

ESLint: 8.56.0

TypeError: Cannot read properties of undefined (reading 'length')
Occurred while linting <snip>.html:1
Rule: "@eslint-community/eslint-comments/disable-enable-pair"
    at Program (<snip>\node_modules\@eslint-community\eslint-plugin-eslint-comments\lib\rules\disable-enable-pair.js:47:49)
    at ruleErrorHandler (<snip>\node_modules\eslint\lib\linter\linter.js:1076:28)      
    at <snip>\node_modules\eslint\lib\linter\safe-emitter.js:45:58
    at Array.forEach (<anonymous>)
    at Object.emit (<snip>\node_modules\eslint\lib\linter\safe-emitter.js:45:38)       
    at NodeEventGenerator.applySelector (<snip>\node_modules\eslint\lib\linter\node-event-generator.js:297:26)
    at NodeEventGenerator.applySelectors (<snip>\node_modules\eslint\lib\linter\node-event-generator.js:326:22)
    at NodeEventGenerator.enterNode (<snip>\node_modules\eslint\lib\linter\node-event-generator.js:340:14)
    at CodePathAnalyzer.enterNode (<snip>\node_modules\eslint\lib\linter\code-path-analysis\code-path-analyzer.js:803:23)
    at <snip>\node_modules\eslint\lib\linter\linter.js:1111:32
```

**Comment by Samuel-Therrien-Beslogic** [comment]
Hi, can this be reopenned? (CC @MichaelDeBoey @eslint-community , see https://github.com/eslint-community/eslint-plugin-eslint-comments/issues/164 )

**Comment by scagood** [comment]
Can you try to reproduce this error in the playground?

https://eslint-online-playground.netlify.app/#eNqdkcFOwzAMhl/FymXStLYgAUKdkDggXoED2SFrvZGROiVJYVPVd8dJypg4ckkV//6/2n9G4V1T4VF1vcHy4EUtqiWgN5pC0WqvtgbhY7ABPSwrSZIaSz6AggdYbBdrsRK5ueT6Tu8zQne9dQEOHnbOdiDFY26qDl6KtaRZb2zXIYW/XUWsD6TDqZoLvRn2mooLOdoSShIeE6zFnRpMgFdJAGM8ALLP1zD+/mtaZc0NBqOSbzAvWbNfoHPWSbHikVo7cAJSbGYXcO0HVc35FEjp0yvNLiZwzxkx8kUZY79e3qzBZx1hNQQ3IEywydA8Ujw3vBFH2qvmXe3je1jiONOMUoRTn8xSdLbl6RmfhRY/n7BHapEajZzLea1/ZBr5N+V1eTXjLyDp+aJuFEcVLhqynsX78vYuutNOkiYxfQMnK8xI

**Comment by Samuel-Therrien-Beslogic** [comment]
> Can you try to reproduce this error in the playground?
> 
> [eslint-online-playground.netlify.app](https://eslint-online-playground.netlify.app/#eNqdkcFOwzAMhl/FymXStLYgAUKdkDggXoED2SFrvZGROiVJYVPVd8dJypg4ckkV//6/2n9G4V1T4VF1vcHy4EUtqiWgN5pC0WqvtgbhY7ABPSwrSZIaSz6AggdYbBdrsRK5ueT6Tu8zQne9dQEOHnbOdiDFY26qDl6KtaRZb2zXIYW/XUWsD6TDqZoLvRn2mooLOdoSShIeE6zFnRpMgFdJAGM8ALLP1zD+/mtaZc0NBqOSbzAvWbNfoHPWSbHikVo7cAJSbGYXcO0HVc35FEjp0yvNLiZwzxkx8kUZY79e3qzBZx1hNQQ3IEywydA8Ujw3vBFH2qvmXe3je1jiONOMUoRTn8xSdLbl6RmfhRY/n7BHapEajZzLea1/ZBr5N+V1eTXjLyDp+aJuFEcVLhqynsX78vYuutNOkiYxfQMnK8xI)

Doesn't look like the playground supports HTML files:
`File ignored because of a matching ignore pattern. Use "--no-ignore" to disable file ignore settings or use "--no-warn-ignored" to suppress this warning.`
